apiVersion: v2
name: sekai-master-api
description: Split-role Kubernetes deployment for sekai-master-api
type: application
version: 0.1.0
appVersion: "latest"
kubeVersion: ">=1.24.0-0"
annotations:
  artifacthub.io/license: MIT
