root = "."
tmp_dir = "tmp/air"

[build]
cmd = "go build -buildvcs=false -o ./tmp/air/main ./cmd/api"
entrypoint = "./tmp/air/main"
include_ext = ["go", "env"]
exclude_dir = ["tmp", "bin", ".git", ".devcontainer"]
exclude_file = []
exclude_regex = ["_test\\.go"]
delay = 300
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"
poll = true
poll_interval = 500

[log]
time = true

[color]
main = "cyan"
watcher = "yellow"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true
