#!/usr/bin/env sh
set -eu

. ./.mise/lib/tasks.sh
load_app_env

dsn="${DATABASE_URL:-postgres://sekai:sekai@${COMPOSE_HOST}:5432/sekai?sslmode=disable}"

echo "[migrate-up] APP_ENV=${APP_ENV} DIALECT=postgres"
go run -buildvcs=false github.com/pressly/goose/v3/cmd/goose@latest -dir internal/storage/migrations postgres "$dsn" up
